name: Build and Deploy to Google Compute Engine

on:
  push:
    branches:
    - master

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: ${{ secrets.GCE_INSTANCE }}
  GCE_INSTANCE_ZONE: ${{ secrets.GCE_INSTANCE_ZONE }}
  GCLOUD_USER: ${{ secrets.GCLOUD_USER }}
jobs:
  setup-build-publish-deploy:
    name: Setup, and Deploy
    runs-on: ubuntu-latest

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCE_SA_KEY }}'

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCE_PROJECT }}
    
    - name: SSH
      run: |-
          gcloud compute ssh $GCLOUD_USER@$GCE_INSTANCE --zone=$GCE_INSTANCE_ZONE --command="./update_bot"
    
